// Shared types for the game engine, Firebase layer, and UI.
// This file is the contract between game/, firebase/, and components/ — keep additions additive.

export type Resource = 'brick' | 'lumber' | 'ore' | 'grain' | 'wool';
export const RESOURCES: Resource[] = ['brick', 'lumber', 'ore', 'grain', 'wool'];

export type ResourceCount = Record<Resource, number>;

// 'gold' produces no fixed resource — rolling it lets each adjacent settlement/city owner
// pick any 1 resource (2 for a city) instead, via the 'pickGoldResources' action/'goldPick'
// phase. Currently only used by the 'fog-of-war' preset.
export type Terrain = 'hills' | 'forest' | 'mountains' | 'fields' | 'pasture' | 'desert' | 'gold';

export const TERRAIN_RESOURCE: Record<Exclude<Terrain, 'desert' | 'gold'>, Resource> = {
  hills: 'brick',
  forest: 'lumber',
  mountains: 'ore',
  fields: 'grain',
  pasture: 'wool',
};

// Axial hex coordinates (pointy-top).
export interface AxialCoord {
  q: number;
  r: number;
}

export interface HexTile {
  id: string; // `${q},${r}`
  coord: AxialCoord;
  terrain: Terrain;
  // null for desert, or (fog-of-war only) for an undiscovered hex whose number hasn't been
  // randomly assigned yet — see 'fog-of-war' handling in rules.ts.
  number: number | null;
}

export type PortType = Resource | 'generic'; // generic = 3:1

export interface Port {
  id: string;
  vertexIds: [string, string]; // the two vertices that can use this port
  type: PortType;
}

// Vertices and edges are identified by a canonical string id derived from the
// (sorted) hex corners that touch them, generated by board.ts. UI/game code
// should treat these ids as opaque.
export type VertexId = string;
export type EdgeId = string;

export interface VertexInfo {
  id: VertexId;
  // pixel-independent position used for rendering: cube corner shared by up to 3 hexes
  adjacentHexIds: string[];
  adjacentVertexIds: VertexId[];
  adjacentEdgeIds: EdgeId[];
}

export interface EdgeInfo {
  id: EdgeId;
  vertexIds: [VertexId, VertexId];
  adjacentHexIds: string[];
}

export interface Board {
  hexes: HexTile[];
  vertices: Record<VertexId, VertexInfo>;
  edges: Record<EdgeId, EdgeInfo>;
  ports: Port[];
  robberHexId: string;
}

export type MapPresetId = 'official-beginner' | 'balanced-random' | 'chaos' | 'extended-5-6p' | 'fog-of-war';

export interface MapPreset {
  id: MapPresetId;
  name: string;
  description: string;
}

export type BuildingType = 'settlement' | 'city';

export interface Building {
  type: BuildingType;
  uid: string;
}

export type DevCardType = 'knight' | 'roadBuilding' | 'yearOfPlenty' | 'monopoly' | 'victoryPoint';

export interface DevCard {
  id: string;
  type: DevCardType;
  boughtTurn: number;
}

export type GamePhase =
  | 'lobby'
  | 'setup1'
  | 'setup2'
  | 'roll'
  | 'main'
  | 'discard'
  | 'robber'
  // One or more players rolled a gold hex's number and must each pick their resource(s)
  // before play resumes — see pendingGoldPicks on RoomState.
  | 'goldPick'
  | 'gameOver';

export const PLAYER_COLORS = ['red', 'blue', 'white', 'orange', 'green', 'brown'] as const;
export type PlayerColor = (typeof PLAYER_COLORS)[number];

export type BotDifficulty = 'normal';

// --- Public, room-readable player summary (no hidden info) ---
export interface PublicPlayer {
  uid: string;
  displayName: string;
  color: PlayerColor;
  isBot: boolean;
  botDifficulty?: BotDifficulty;
  seatIndex: number;
  resourceCount: number;
  devCardCount: number;
  visibleVictoryPoints: number; // excludes hidden VP dev cards
  knightsPlayed: number;
  roadsBuilt: number;
  settlementsBuilt: number;
  citiesBuilt: number;
  connected: boolean;
  lastSeen: number; // ms epoch, client-set
}

// --- Private per-player hand, readable only by that player ---
export interface PrivateHand {
  resources: ResourceCount;
  devCards: DevCard[];
}

export interface LogEntry {
  id: string;
  ts: number;
  message: string;
}

export type TradeStatus = 'pending' | 'accepted' | 'rejected' | 'cancelled' | 'countered';

export interface TradeOffer {
  id: string;
  proposerUid: string;
  targetUid: string | null; // null = open to all
  give: Partial<ResourceCount>;
  receive: Partial<ResourceCount>;
  status: TradeStatus;
  counterOf: string | null;
  createdAt: number;
  // Open trades (targetUid === null) only: uids who've accepted and are waiting for the
  // proposer to pick one via finalizeTrade. Accepting a *targeted* trade still executes
  // immediately (see respondTrade in rules.ts) since there's only ever one possible
  // responder, so this stays empty for those. Optional so older-shaped docs still typecheck.
  interestedUids?: string[];
}

// --- Room / shared game state document ---
export interface RoomState {
  id: string;
  code: string;
  hostUid: string;
  status: 'lobby' | 'playing' | 'finished';
  mapPreset: MapPresetId;
  // Board layout is a deterministic function of this seed, so it's safe public info. Once a
  // game has started, though, the same seed is also the sole input to the dev-card shuffle
  // (see devCardDeck below) — leaking it after that point is equivalent to leaking the deck
  // order. The startGame Cloud Function generates a fresh seed and never writes the real
  // value to this public field once status is 'playing'; only the pre-game lobby placeholder
  // is meaningful here.
  seed: string;
  board: Board | null; // null until game starts
  vertices: Record<VertexId, Building>; // sparse
  edges: Record<EdgeId, string>; // edgeId -> owner uid, sparse
  turnOrder: string[]; // uids in seat order
  currentPlayerIndex: number;
  phase: GamePhase;
  diceRoll: [number, number] | null;
  bank: ResourceCount;
  devCardDeck: DevCardType[]; // remaining, shuffled. Server-only: the Firestore adapter keeps this out of the public doc (see serverOnly/devDeck) and mirrors its length via devCardDeckCount below.
  devCardDeckCount: number; // public, client-safe mirror of devCardDeck.length
  longestRoadUid: string | null;
  largestArmyUid: string | null;
  winnerUid: string | null;
  turnNumber: number;
  turnStartedAt: number;
  setupRound: 1 | 2 | null;
  pendingDiscardUids: string[]; // players who must discard on a 7
  botActionClaim: { turnNumber: number; ts: number } | null;
  log: LogEntry[];
  createdAt: number;
  // Host-configurable house rules, set at room creation, fixed once status leaves 'lobby'.
  victoryPointsToWin: number; // default DEFAULT_VICTORY_POINTS_TO_WIN
  discardLimit: number; // hand size that triggers a discard on a rolled 7; default DEFAULT_DISCARD_LIMIT
  turnTimerSeconds: number | null; // countdown shown per turn; null = disabled. Enforced server-side via 'timeoutEndTurn'.
  // Non-bot majority vote to freeze/unfreeze the game — see voteToPause/voteToUnpause in
  // rules.ts. While paused, the turn timer and AFK auto-roll both stop counting elapsed time.
  paused: boolean;
  pausedAt: number | null; // Date.now() when `paused` flipped true; used to shift turnStartedAt forward by the pause duration on unpause, so elapsed-time math resumes where it left off.
  pauseVotes: string[]; // uids currently voting to flip `paused` the opposite way of its current value
  // fog-of-war only (null on every other preset): hex ids whose terrain is revealed to
  // players and which produce resources on a roll. Starts as the board's corner hexes, the
  // desert, and the gold hex (see board.ts); a road reaching a new hex reveals it — see
  // 'buildRoad' in rules.ts.
  discoveredHexIds: string[] | null;
  // Players who rolled a gold hex's number this turn and still owe a resource pick (1 per
  // settlement, 2 per city touching it) — see 'pickGoldResources' and the 'goldPick' phase.
  pendingGoldPicks: { uid: string; amount: number }[];
  // Added by game/rules.ts (additive, optional so other constructors aren't broken):
  devCardPlayedThisTurn?: boolean; // at most one dev card may be played per turn
  lastSetupSettlementVertexId?: VertexId | null; // anchors the free setup road to the settlement just placed
}

export const BUILD_COSTS: Record<'road' | 'settlement' | 'city' | 'devCard', Partial<ResourceCount>> = {
  road: { brick: 1, lumber: 1 },
  settlement: { brick: 1, lumber: 1, grain: 1, wool: 1 },
  city: { ore: 3, grain: 2 },
  devCard: { ore: 1, grain: 1, wool: 1 },
};

export const STARTING_BANK: ResourceCount = { brick: 19, lumber: 19, ore: 19, grain: 19, wool: 19 };

export const MAX_ROADS = 15;
export const MAX_SETTLEMENTS = 5;
export const MAX_CITIES = 4;
export const DEFAULT_VICTORY_POINTS_TO_WIN = 10;
export const DEFAULT_DISCARD_LIMIT = 7;
export const DEFAULT_TURN_TIMER_SECONDS = 120;
export const LONGEST_ROAD_MIN = 5;
export const LARGEST_ARMY_MIN = 3;

// --- Game actions: the single vocabulary of legal moves, applied via game/rules.ts ---
export type GameAction =
  | { type: 'rollDice'; uid: string }
  | { type: 'buildRoad'; uid: string; edgeId: EdgeId; free?: boolean }
  | { type: 'buildSettlement'; uid: string; vertexId: VertexId; free?: boolean }
  | { type: 'buildCity'; uid: string; vertexId: VertexId }
  | { type: 'buyDevCard'; uid: string }
  | { type: 'playKnight'; uid: string; devCardId: string; robberHexId: string; stealFromUid: string | null }
  | { type: 'playRoadBuilding'; uid: string; devCardId: string; edgeIds: [EdgeId, EdgeId] }
  | { type: 'playYearOfPlenty'; uid: string; devCardId: string; resources: [Resource, Resource] }
  | { type: 'playMonopoly'; uid: string; devCardId: string; resource: Resource }
  | { type: 'moveRobber'; uid: string; robberHexId: string; stealFromUid: string | null } // post-7 roll, no card
  | { type: 'discard'; uid: string; resources: Partial<ResourceCount> }
  // fog-of-war only: pays out a pending gold-hex pick (see pendingGoldPicks/'goldPick' phase).
  // resources.length must exactly match the owed amount; entries need not be distinct.
  | { type: 'pickGoldResources'; uid: string; resources: Resource[] }
  | { type: 'bankTrade'; uid: string; give: Resource; giveAmount: number; receive: Resource }
  | { type: 'proposeTrade'; uid: string; give: Partial<ResourceCount>; receive: Partial<ResourceCount>; targetUid: string | null }
  | { type: 'respondTrade'; uid: string; tradeId: string; accept: boolean }
  | { type: 'cancelTrade'; uid: string; tradeId: string }
  // Proposer-only: picks one of an open trade's interestedUids to actually execute the
  // swap with. Targeted trades never need this — accepting one executes immediately via
  // respondTrade, since there's only ever one possible responder.
  | { type: 'finalizeTrade'; uid: string; tradeId: string; withUid: string }
  | { type: 'endTurn'; uid: string }
  // uid === targetUid is a self-leave; otherwise uid must be the host removing a bot seat.
  // Only legal outside setup1/setup2 (see rules.ts) — the snake-ordered setup turn sequence
  // doesn't generalize cleanly to a mutating turnOrder mid-snake.
  | { type: 'removeSeat'; uid: string; targetUid: string }
  // Any room member may submit this once the current turn's clock has actually run out
  // server-side (re-validated in rules.ts, never trusted from the client) — advances the
  // turn exactly like endTurn, crediting the timeout to whoever was current, not the caller.
  | { type: 'timeoutEndTurn'; uid: string }
  // uid casts (or withdraws) a vote to flip `paused` the opposite way of its current value.
  // Bots never vote; majority is computed over non-bot turnOrder members only.
  | { type: 'voteToPause'; uid: string }
  | { type: 'voteToUnpause'; uid: string };
