// Shared types for the game engine, Firebase layer, and UI.
// This file is the contract between game/, firebase/, and components/ — keep additions additive.

export type Resource = 'brick' | 'lumber' | 'ore' | 'grain' | 'wool';
export const RESOURCES: Resource[] = ['brick', 'lumber', 'ore', 'grain', 'wool'];

export type ResourceCount = Record<Resource, number>;

export type Terrain = 'hills' | 'forest' | 'mountains' | 'fields' | 'pasture' | 'desert';

export const TERRAIN_RESOURCE: Record<Exclude<Terrain, 'desert'>, Resource> = {
  hills: 'brick',
  forest: 'lumber',
  mountains: 'ore',
  fields: 'grain',
  pasture: 'wool',
};

// Axial hex coordinates (pointy-top).
export interface AxialCoord {
  q: number;
  r: number;
}

export interface HexTile {
  id: string; // `${q},${r}`
  coord: AxialCoord;
  terrain: Terrain;
  number: number | null; // null for desert
}

export type PortType = Resource | 'generic'; // generic = 3:1

export interface Port {
  id: string;
  vertexIds: [string, string]; // the two vertices that can use this port
  type: PortType;
}

// Vertices and edges are identified by a canonical string id derived from the
// (sorted) hex corners that touch them, generated by board.ts. UI/game code
// should treat these ids as opaque.
export type VertexId = string;
export type EdgeId = string;

export interface VertexInfo {
  id: VertexId;
  // pixel-independent position used for rendering: cube corner shared by up to 3 hexes
  adjacentHexIds: string[];
  adjacentVertexIds: VertexId[];
  adjacentEdgeIds: EdgeId[];
}

export interface EdgeInfo {
  id: EdgeId;
  vertexIds: [VertexId, VertexId];
  adjacentHexIds: string[];
}

export interface Board {
  hexes: HexTile[];
  vertices: Record<VertexId, VertexInfo>;
  edges: Record<EdgeId, EdgeInfo>;
  ports: Port[];
  robberHexId: string;
}

export type MapPresetId = 'official-beginner' | 'balanced-random' | 'chaos';

export interface MapPreset {
  id: MapPresetId;
  name: string;
  description: string;
}

export type BuildingType = 'settlement' | 'city';

export interface Building {
  type: BuildingType;
  uid: string;
}

export type DevCardType = 'knight' | 'roadBuilding' | 'yearOfPlenty' | 'monopoly' | 'victoryPoint';

export interface DevCard {
  id: string;
  type: DevCardType;
  boughtTurn: number;
}

export type GamePhase =
  | 'lobby'
  | 'setup1'
  | 'setup2'
  | 'roll'
  | 'main'
  | 'discard'
  | 'robber'
  | 'gameOver';

export const PLAYER_COLORS = ['red', 'blue', 'white', 'orange', 'green', 'brown'] as const;
export type PlayerColor = (typeof PLAYER_COLORS)[number];

export type BotDifficulty = 'normal';

// --- Public, room-readable player summary (no hidden info) ---
export interface PublicPlayer {
  uid: string;
  displayName: string;
  color: PlayerColor;
  isBot: boolean;
  botDifficulty?: BotDifficulty;
  seatIndex: number;
  resourceCount: number;
  devCardCount: number;
  visibleVictoryPoints: number; // excludes hidden VP dev cards
  knightsPlayed: number;
  roadsBuilt: number;
  settlementsBuilt: number;
  citiesBuilt: number;
  connected: boolean;
  lastSeen: number; // ms epoch, client-set
}

// --- Private per-player hand, readable only by that player ---
export interface PrivateHand {
  resources: ResourceCount;
  devCards: DevCard[];
}

export interface LogEntry {
  id: string;
  ts: number;
  message: string;
}

export type TradeStatus = 'pending' | 'accepted' | 'rejected' | 'cancelled' | 'countered';

export interface TradeOffer {
  id: string;
  proposerUid: string;
  targetUid: string | null; // null = open to all
  give: Partial<ResourceCount>;
  receive: Partial<ResourceCount>;
  status: TradeStatus;
  counterOf: string | null;
  createdAt: number;
}

// --- Room / shared game state document ---
export interface RoomState {
  id: string;
  code: string;
  hostUid: string;
  status: 'lobby' | 'playing' | 'finished';
  mapPreset: MapPresetId;
  seed: string;
  board: Board | null; // null until game starts
  vertices: Record<VertexId, Building>; // sparse
  edges: Record<EdgeId, string>; // edgeId -> owner uid, sparse
  turnOrder: string[]; // uids in seat order
  currentPlayerIndex: number;
  phase: GamePhase;
  diceRoll: [number, number] | null;
  bank: ResourceCount;
  devCardDeck: DevCardType[]; // remaining, shuffled, order hidden by convention (not truly secret client-side)
  longestRoadUid: string | null;
  largestArmyUid: string | null;
  winnerUid: string | null;
  turnNumber: number;
  turnStartedAt: number;
  setupRound: 1 | 2 | null;
  pendingDiscardUids: string[]; // players who must discard on a 7
  botActionClaim: { turnNumber: number; ts: number } | null;
  log: LogEntry[];
  createdAt: number;
  // Host-configurable house rules, set at room creation, fixed once status leaves 'lobby'.
  victoryPointsToWin: number; // default DEFAULT_VICTORY_POINTS_TO_WIN
  discardLimit: number; // hand size that triggers a discard on a rolled 7; default DEFAULT_DISCARD_LIMIT
  turnTimerSeconds: number | null; // countdown shown per turn; null = disabled. Informational only, not enforced.
  // Added by game/rules.ts (additive, optional so other constructors aren't broken):
  devCardPlayedThisTurn?: boolean; // at most one dev card may be played per turn
  lastSetupSettlementVertexId?: VertexId | null; // anchors the free setup road to the settlement just placed
}

export const BUILD_COSTS: Record<'road' | 'settlement' | 'city' | 'devCard', Partial<ResourceCount>> = {
  road: { brick: 1, lumber: 1 },
  settlement: { brick: 1, lumber: 1, grain: 1, wool: 1 },
  city: { ore: 3, grain: 2 },
  devCard: { ore: 1, grain: 1, wool: 1 },
};

export const STARTING_BANK: ResourceCount = { brick: 19, lumber: 19, ore: 19, grain: 19, wool: 19 };

export const MAX_ROADS = 15;
export const MAX_SETTLEMENTS = 5;
export const MAX_CITIES = 4;
export const DEFAULT_VICTORY_POINTS_TO_WIN = 10;
export const DEFAULT_DISCARD_LIMIT = 7;
export const DEFAULT_TURN_TIMER_SECONDS = 120;
export const LONGEST_ROAD_MIN = 5;
export const LARGEST_ARMY_MIN = 3;

// --- Game actions: the single vocabulary of legal moves, applied via game/rules.ts ---
export type GameAction =
  | { type: 'rollDice'; uid: string }
  | { type: 'buildRoad'; uid: string; edgeId: EdgeId; free?: boolean }
  | { type: 'buildSettlement'; uid: string; vertexId: VertexId; free?: boolean }
  | { type: 'buildCity'; uid: string; vertexId: VertexId }
  | { type: 'buyDevCard'; uid: string }
  | { type: 'playKnight'; uid: string; devCardId: string; robberHexId: string; stealFromUid: string | null }
  | { type: 'playRoadBuilding'; uid: string; devCardId: string; edgeIds: [EdgeId, EdgeId] }
  | { type: 'playYearOfPlenty'; uid: string; devCardId: string; resources: [Resource, Resource] }
  | { type: 'playMonopoly'; uid: string; devCardId: string; resource: Resource }
  | { type: 'moveRobber'; uid: string; robberHexId: string; stealFromUid: string | null } // post-7 roll, no card
  | { type: 'discard'; uid: string; resources: Partial<ResourceCount> }
  | { type: 'bankTrade'; uid: string; give: Resource; giveAmount: number; receive: Resource }
  | { type: 'proposeTrade'; uid: string; give: Partial<ResourceCount>; receive: Partial<ResourceCount>; targetUid: string | null }
  | { type: 'respondTrade'; uid: string; tradeId: string; accept: boolean }
  | { type: 'cancelTrade'; uid: string; tradeId: string }
  | { type: 'endTurn'; uid: string };
